### ISSUE TITLE
Providing EIP  does not work

### ISSUE THREAD

**Issue by JasonCarter80** [AviatrixSystems/terraform-provider-aviatrix#100]
I've tore down my entire setup and rebuilt, but retained the EIP attached to my OpenVPN gateways.  When rebuilding I've assigned the EIP to each, no dice.    Assigned EIP and set allocate_new_eip = "no" yet I still get a new EIP assigned with my old one remaining unassigned.   

Am I doing this wrong or is the assignment of EIP via Terraform broken?

**Comment by arvindsree** [comment]
This feature is not supported, yet. The current "eip" attribute is only a computed value that returns the EIP of the created gateway

**Comment by arvindsree** [comment]
Ignore my previous comment. 

The correct value for "allocate_new_eip" should be "off" (REST API does not seem to have a consistent notation for boolean). 
Also the "eip" parameter must be passed when allocate_new_eip is "off". The "eip" should be the IP that is to be allocated.

Example:
resource "aviatrix_gateway" "vpn-gateway-test" {
  cloud_type   = 1
  account_name = "aws"
  gw_name      = "gw12"
  vpc_id       = "vpc-zxczxczxc"
  vpc_reg      = "us-east-2"
  vpc_size     = "t2.micro"
  vpc_net      = "172.31.0.0/20"
  allocate_new_eip = "off"
  eip = "52.17.7.36"
}



We will update the docs

**Comment by JasonCarter80** [comment]
Indeed that does work, thank you.
