### ISSUE TITLE
Broken Link to Compatibility Chart

### ISSUE THREAD

**Issue by terensapp** [AviatrixSystems/terraform-provider-aviatrix#1182]
On the main doc page: https://registry.terraform.io/providers/AviatrixSystems/aviatrix/latest/docs The link to "compatibility chart" includes .html which causes the link to break, removing the .html resolves the issue.

**Comment by zhiqiangjin** [comment]
This issue will be resolved in our next release, which be released by the end of February.

**Comment by zhiqiangjin** [comment]
This issue has been fixed in 2.21.1-6.6.ga release. Close it for now.
