### ISSUE TITLE
AWS peer Import Having issues with Routetable

### ISSUE THREAD

**Issue by Manickavel** [AviatrixSystems/terraform-provider-aviatrix#1399]
While trying to import the AWS peer we are facing issues with routetable ,Its doesn't import routetable list to state file ,so after import if we try to plan it again Replace the VPC Peering `by updating the routetable list

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

Import VPC peering with routable list

Try Terraform plan

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

**Expected behavior** Routetable list should be imported to state file and next terraform plan should not make any changes

**Additional data / screenshots**
Include any relevant tf files.

**Environment:**
 - Provider version  2.22.0
 - Terraform version 1.2.9
 - Aviatrix Controller version :6.7.1186

**Additional context**
What was the impact? Unable to import manually created VPC peering

**Comment by zhiqiangjin** [comment]
https://github.com/AviatrixSystems/terraform-provider-aviatrix/pull/1443
It will be fixed in next release, which will be 3.0.0 compatible with controller 7.0.
