### ISSUE TITLE
spoke gateway snat custom mode / policy_list not supported

### ISSUE THREAD

**Issue by tkellen** [AviatrixSystems/terraform-provider-aviatrix#145]
Hi again ya'll!

I'm in the process of expanding our usage of this provider and ran into an issue where the handler for `aviatrix_spoke_gateway` resources is missing support for some things your API documentation indicates are available (`POST https://{{controller_hostname}}/v1/api` with an action of `enable_snat`):
https://api.aviatrix.com/?version=latest#a8271731-01fd-46c6-b0a6-d243d1131ad3

Here is roughly what I think the config would look like?
```
resource "aviatrix_spoke_gateway" "main" {
  enable_snat = true
... BEGIN MISSING
  mode        = "custom"
  policy_list = {
    connection = "None"
    dst_ip = ...
    dst_port = ...
    exclude_rtb = ...
    interface = ...
    new_src_ip = ...
    src_cidr = ...
    protocol = ...
    src_port = ...
  }
... END MISSING
```

I'm unsure if the configuration as defined above is actually what is needed, but it seems to follow the examples in the API. 

Is there a chance you could expand the provider to support this? If so, could you share a sense of how far off that support would be? Assuming the answer is no, or the runway is more than a week or two, I would be happy to submit a PR if you could provide a skeleton example of how you'd like to see this configuration exposed.

Thanks in advance for any guidance you can provide.

**Comment by tkellen** [comment]
Anyone out there?

**Comment by inc1t3Ful** [comment]
Hi Tyler!

Apologies for the late response. We could definitely expand our provider to support this. I will have to check with the team on any ETA, because we are scheduling a release within this week (tomorrow) already so this enhancement request will at earliest can be fit into the next release which generally should be in 2 weeks.

I'll be sure to update here on any information!

**Comment by tkellen** [comment]
Thanks for the reply @inc1t3Ful! Two weeks from now sounds just fine! If it turns out this is months away please let me know and I'd be glad to make a contribution to add the functionality.

**Comment by inc1t3Ful** [comment]
Just confirmed with the team, we should be able to fit it into the next release in around 2 weeks :)

**Comment by inc1t3Ful** [comment]
Hi @tkellen ! My apologies but due to unforeseen circumstances, and upon further review, this implementation will have to be pushed back to the next release 2.9.0, which would be around the next 2 weeks. 

However, in addition to support for custom SNAT mode for spoke, we also plan to expand to support custom DNAT as well, for all gateway-type resources (gateway, spoke and transit gateway)

**Comment by tkellen** [comment]
Thanks so much for the update and no worries at all about the delay, this is free after all :smile:

**Comment by inc1t3Ful** [comment]
Hi @tkellen ! Our provider v2.9.0 has been released and it includes support for singleIP, multi-IP and custom SNAT for spoke gateways (AWS and ARM), and custom DNAT support for regular gateways and spoke gateways (AWS and ARM). 

Please let us know how it works out for you!

Release notes:
https://www.terraform.io/docs/providers/aviatrix/guides/release-notes.html#2-9-0

**Comment by tkellen** [comment]
Hi ya'll! Thank you so much for working on this. It's much closer, but not quite
there. I believe we need to control snat/dnat policies with a separate resource
rather than placing them inline on the `aviatrix_spoke_gateway`.

There are two reasons for this:

1. With the current functionality there is no way to place a unique policy on
both the primary and secondary spoke when HA is enabled. Adding `ha_dnat_policy`
and `ha_snat_policy` blocks could do the trick, but that would still be broken.

2. The `new_src_ip` in my snat policies needs to be the private IP for one of
the gateways that the `aviatrix_spoke_gateway` creates. I can only look up that
IP after it has been created. Here's a sample config showing the recursive loop
that results:

```
resource "aviatrix_spoke_gateway" "main" {
  cloud_type         = 1
  account_name       = "<redacted>"
  gw_name            = "<redacted>"
  vpc_id             = local.foundation.vpc.id // defined elsewhere, not shown here for brevity
  vpc_reg            = "us-east-1"
  gw_size            = "c5.large"
  subnet             = local.foundation.vpc.public_subnet_cidr_blocks[0] // defined elsewhere, not shown here for brevity
  transit_gw         = "<redacted>-us-east-1-transitmesh-aviatrixGW"
  enable_active_mesh = true
  enable_snat        = true
  snat_mode          = "custom"
  snat_policy {
    src_ip = local.foundation.vpc.cidr_block // defined elsewhere, not shown here for brevity
    dst_ip = "0.0.0.0/0"
    interface = "eth0"
    new_src_ip = data.aws_instance.primary_gateway.private_ip // cannot be resolved at initial create time
  }
}

// find the private ip of the gateway, this is recursive, it doesn't exist yet
data "aws_instance" "primary_gateway" {
  instance_id = aviatrix_spoke_gateway.main.cloud_instance_id
}
```

This style of config would resolve the issue:
```
resource "aviatrix_spoke_gateway" "main" {
  cloud_type         = 1
  account_name       = "<redacted>"
  gw_name            = "<redacted>"
  vpc_id             = local.foundation.vpc.id // defined elsewhere, not shown here for brevity
  vpc_reg            = "us-east-1"
  gw_size            = "c5.large"
  subnet             = local.foundation.vpc.public_subnet_cidr_blocks[0] // defined elsewhere, not shown here for brevity
  ha_subnet          = local.foundation.vpc.public_subnet_cidr_blocks[1] // defined elsewhere, not shown here for brevity
  ha_gw_size         = "c5.large"
  transit_gw         = "<redacted>"
  enable_active_mesh = true
  enable_snat        = true
  snat_mode          = "custom"
}

// look up the private ip of the primary spoke
data "aws_instance" "primary_gateway" {
  instance_id = aviatrix_spoke_gateway.main.cloud_instance_id
}

// look up the private ip of the ha spoke gateway (needs a new attribute, `ha_cloud_instance_id`)
data "aws_instance" "ha_gateway" {
  instance_id = aviatrix_spoke_gateway.main.ha_cloud_instance_id
}

// assign snat policy to primary spoke gateway
resource "aviatrix_snat_policy" "primary" {
  spoke_gateway_id = aviatrix_spoke_gateway.main.id
  src_ip           = local.foundation.vpc.cidr_block // defined elsewhere, not shown here for brevity
  dst_ip           = "0.0.0.0/0"
  interface        = "eth0"
  new_src_ip       = data.aviatrix_gateway.primary_gateway.private_ip // now a separate resource whose creation is dependent on the data resource which itself is dependent on the creation of the spoke gateway
}

// assign snat policy to ha spoke gateway (needs a new attribute, `ha_id`)
resource "aviatrix_snat_policy" "ha" {
  spoke_gateway_id = aviatrix_spoke_gateway.main.ha_id
  src_ip           = local.foundation.vpc.cidr_block // defined elsewhere, not shown here for brevity
  dst_ip           = "0.0.0.0/0"
  interface        = "eth0"
  new_src_ip       = data.aviatrix_gateway.ha_gateway.private_ip // now a separate resource whose creation is dependent on the data resource which itself is dependent on the creation of the spoke gateway
}
```

This mirrors the manual workflow used today (create the spoke gateway in one
step, enable snat with the appropriate config after manually locating the needed
resources that were created in the first step) but can be applied in one step
thanks to terraform's dependency graph.

---

Finally, when I tried to mirror this multi-step manual workflow in terraform
without HA mode the following error resulted:
```
 # aviatrix_spoke_gateway.main will be updated in-place
  ~ resource "aviatrix_spoke_gateway" "main" {
        account_name          = "<redacted>"
        allocate_new_eip      = true
        cloud_instance_id     = "<redacted>"
        cloud_type            = 1
        eip                   = "<redacted>"
        enable_active_mesh    = true
        enable_encrypt_volume = false
      ~ enable_snat           = false -> true
        enable_vpc_dns_server = false
        gw_name               = "<redacted>"
        gw_size               = "c5.large"
        id                    = "<redacted>"
        insane_mode           = false
        single_az_ha          = false
      ~ snat_mode             = "primary" -> "custom" // changed after initial creation and manual lookup
        subnet                = "10.132.147.192/28"
        tag_list              = []
        transit_gw            = "<redacted>"
        vpc_id                = "<redacted>"
        vpc_reg               = "us-east-1"

      + snat_policy { // added after initial creation and manual lookup
          + connection = "None"
          + dst_ip     = "0.0.0.0/0"
          + interface  = "eth0"
          + new_src_ip = "10.132.147.197"
          + src_ip     = "10.132.144.0/22" 
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aviatrix_spoke_gateway.main: Modifying... [id=<redacted>]

Error: couldn't get detail information of Aviatrix Spoke Gateway: <redacted> due to: Json Decode list_vpc_by_name failed: json: cannot unmarshal string into Go struct field GatewayDetail.snat_ip_port_list of type []goaviatrix.PolicyRule
```

**Comment by tkellen** [comment]
Also, we are on `UserConnect-5.1` and I had to add the skip version check flag to the provider so perhaps that speaks to the final error shown in the commentary above?

**Comment by tkellen** [comment]
...one last note, we will be updating to UserConnect-5.2 in January. Assuming ya'll are willing to iterate on the implementation as described above we will be ready to test properly then.

**Comment by inc1t3Ful** [comment]
Hi @tkellen ! Happy New Years! Thank you so much for the feedback. Yes, the 2.9 release is compatible with UserConnect-5.2, not 5.1.

I will pass on this information and we will definitely iterate on the implementation with consideration to your feedback as well as others we have received. We currently do not have an ETA for you but I will definitely check with the team and update here as soon as I can!

**Comment by tkellen** [comment]
Hi @inc1t3Ful, sorry for the slow reply. Thanks for the update! Any chance things have evolved to a state where you have a sense when some version of the changes I described might be implemented? Failing that, would your team review a contribution from me that implements some or all of the changes I suggested?

**Comment by tkellen** [comment]
Gentle ping to hear your thoughts on my last comment?

**Comment by inc1t3Ful** [comment]
Hi @tkellen , from what I understand from the team, the changes you requested (having the SNAT policies for the spoke gw be managed as a separate resource), should be ETA 2 weeks. Apologies, since there are some unexpected high-priority tasks that have come up.

**Comment by tkellen** [comment]
Sounds good, thanks so much for the update and your continued efforts on this feature--it will make a big difference over here!

**Comment by zhiqiangjin** [comment]
Available in Aviatrix Terraform provider 2.10.0.

**Comment by inc1t3Ful** [comment]
Hi @tkellen ! Our provider v2.10 has been released and now you can manage the customized SNAT and DNAT policies as separate resources (**aviatrix_gateway_snat** and **aviatrix_gateway_dnat** respectively).

Please let us know how it works out for you! Feel free to reopen this issue if you run into any problems.

Please see the release notes for full details: https://www.terraform.io/docs/providers/aviatrix/guides/release-notes.html#2-10-0

**Comment by tkellen** [comment]
Thank you so much @inc1t3Ful! I am out of the country for two weeks but I will definitely let you know how it goes when I get back :D

**Comment by tkellen** [comment]
Sorry for the huge delay in responding here. Just wanted to let you know that I validated this works today. Thank you so much, this is really really slick!
