### ISSUE TITLE
Login failure due to symbols in password value

### ISSUE THREAD

**Issue by jaferrando** [AviatrixSystems/terraform-provider-aviatrix#16]
The URL used to call the controller API does not sanitize the password value to be used in a URL parameter.  Passwords including offending symbols in URLs, though valid, fail to login.

An example:

 https://<my-controller-ip>/v1/api?action=login&username=Admin&password=rt+ItDk%C4MA

**Comment by AviatrixSystems** [comment]
Hi,
If you use POST method, it takes care of special characters. Example:
curl -k --data "action=login" --data "username=admin" --data "password=Aviatrix123!" "https://10.123.123.123/v1/api"

Please refer to updated doc: 
https://s3-us-west-2.amazonaws.com/avx-apidoc/index.htm#api-doc-initial-setup

**Comment by edumanig** [comment]
Just fix the login issue with special characters.  No change needed from your terraform files. Please update your local repo and build.  You can verify the fix using "terraform plan".
