### ISSUE TITLE
Terrform plan still shows the aws instances related to gateway after previous successful apply

### ISSUE THREAD

**Issue by arvindsree** [AviatrixSystems/terraform-provider-aviatrix#167]
![image](https://user-images.githubusercontent.com/21178759/68642802-23dcde80-04c4-11ea-9b2d-2e315df2367a.png)

Created from https://github.com/AviatrixSystems/terraform-provider-aviatrix/issues/647 on behalf of @infa-apatel

**Comment by arvindsree** [comment]
Which version of aviatrix terraform provider and controller are you using? 

Seems like you are trying to add a backup gateway for site2cloud. The controller itself doesn't allow to update it, which is why it probably tainted the resource and is asking you to re-create it. 

aws_instance is part of the aws provider and would be managed outside aviatrix provider. Did you import an aviatrix gateway as an aws_instance (this would probably go out of sync if you did something like a gateway replace)?

**Comment by infa-apatel** [comment]
Terraform : 0.12.13
Controller : 5.1 
Aviatrix Plug in : 2.16 

As I stated, I am not adding anything or making change between step 3 and 4.  Step 3 completes successfully without any problem.  Step 4 should not show any changes, but it still shows the changes I mentioned above.  

1. terraform init
2. terraform plan
3. terraform apply
4. terraform plan

**Comment by arvindsree** [comment]
Could you share the relevant terraform code that caused this behaviour? Site2cloud resource should not be doing this with/without H/A

**Comment by arvindsree** [comment]
It seems that this was a unsupported configuration. Updated the provider to show an error message for this config. This will go in 2.8 provider release
