### ISSUE TITLE
Feature request: Support tagging of AWS peering

### ISSUE THREAD

**Issue by Thamrius** [AviatrixSystems/terraform-provider-aviatrix#173]
With VPC peering, it is very difficult to know which peering is for which vpcs. The ability to create the name tag is the best way to quickly see the connections that are peered. We are looking for support to at least edit the name tag for peering connections through terraform. Currently it looks like just vpc1.vpc2.

**Comment by zhiqiangjin** [comment]
Thanks for your suggestion. We will work on it.

**Comment by zhiqiangjin** [comment]
Do you want a name tag in Terraform only, or you want it to be in aws as well?

**Comment by Thamrius** [comment]
We were looking to see if we could get both. It would greatly help in quickly looking and knowing which connection belongs to which.

**Comment by arvindsree** [comment]
Ref: 8790

**Comment by arvindsree** [comment]
Mode to https://github.com/terraform-providers/terraform-provider-aviatrix/issues/35
