### ISSUE TITLE
Support Import

### ISSUE THREAD

**Issue by jaferrando** [AviatrixSystems/terraform-provider-aviatrix#18]
Support import at least for basic configuration resources (accounts)

**Comment by AviatrixSystems** [comment]
Thanks for your feedback. We are looking into this.

**Comment by zhiqiangjin** [comment]
Imports for gateway and vpn_user resources are supported now

**Comment by arvindsree** [comment]
Import is supported for all resources now. See the  [docs](https://github.com/AviatrixSystems/terraform-provider-aviatrix/tree/master/website/docs/r/) on how to use them

**Comment by jalvarezferr** [comment]
Great! Thanks for this so much looked forward for feature
