### ISSUE TITLE
Support profiles, profile rules and attaching users to profiles

### ISSUE THREAD

**Issue by jaferrando** [AviatrixSystems/terraform-provider-aviatrix#19]
I'd suggest implementing profiles with a similar structure as AWS NACLs:

resource "aviatrix_vpn_profile" "profile" {
  name = "MyProfile"
  basePolicy = ["allow"/"deny"]

  policy {
    protocol   = "tcp"
    action     = "allow"
    target = "10.3.0.0/18"
    portRange    = "443:443"
  }

  policy {
    protocol   = "tcp"
    action     = "allow"
    target = "10.3.0.0/18"
    portRange    = "80:80"
  }

  user_attachment {
     user_name = "${aviatrix_vpn_user.myUser.user_name}"
  }
}

**Comment by AviatrixSystems** [comment]
Thanks for your suggestion, we are working on it. ETA is 6/18. Would that work for you?

**Comment by jb-smoker** [comment]
Any update on this? I'm also interested in using terraform for profile and vpn user management.

**Comment by arvindsree** [comment]
New ETA is end of September. Thanks

**Comment by arvindsree** [comment]
Hi there, this has been added. This is the format of the resource

provider "aviatrix" {
  controller_ip = "a.b.c.d"
  username = "admin"
  password = "xxyy"
}
resource "aviatrix_profile" "terr_profile" {
  name = "profile"
  base_rule = "allow_all"
  policy = [
      {
        action = "allow"
        proto = "tcp" 
        port = "5544"
        target = "10.0.0.0/32"
      },
      {
        action = "allow"
        proto = "tcp" 
        port = "5244"
        target = "11.0.0.0/32"
        }
      ]
  users = ["jj"]
}
