### ISSUE TITLE
Feature and Question for aviatrix spoke

### ISSUE THREAD

**Issue by hotdawg789** [AviatrixSystems/terraform-provider-aviatrix#255]
Not necessarily an issue, but for resource "aviatrix_spoke_vpc" " is the vpc_size the instance size of the to be deployed gateway? odd naming convention, if so. 

For   tag_list = ["k1:v1","k2:v2"]. could this be changed to support a dict of tags vs a list of k:v pairs? similar example is aws provider for terraform, as seen below.  Reason being, we have our "aviatrix_spoke_vpc" "test_spoke_vpc", deployment from a Jenkins pipline, every subsequent terraform init/plan/apply wants to re-apply tags, which are identical but the index order is not persistent. 

```
resource "aviatrix_spoke_vpc" "test_spoke_vpc" {
  cloud_type = 1
  account_name = "${aviatrix_account.test.account_name}"
  gw_name = "tfg-%[1]s"
  vpc_id = "%[5]s"
  vpc_reg = "%[6]s"
  vpc_size = "t2.micro"
  subnet = "%[7]s"
  enable_nat = "no"
  tag_list = ["k1:v1","k2:v2"]
}
```

AWS PROVIDER EXAMPLE 
```
resource "aws_instance" "web" {
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"

  tags = {
    Name = "HelloWorld"
  }
}
```

Proposed change: 
```
resource "aviatrix_spoke_vpc" "test_spoke_vpc" {
  cloud_type = 1
  account_name = "${aviatrix_account.test.account_name}"
  gw_name = "tfg-%[1]s"
  vpc_id = "%[5]s"
  vpc_reg = "%[6]s"
  vpc_size = "t2.micro"
  subnet = "%[7]s"
  enable_nat = "no"
  tags = {
    k1 = "v1"
    k2 = "v2"
  }
}
```

**Comment by arvindsree** [comment]
Agree with that.  These have been carried over from the REST API naming conventions from a long time ago where the gateway was synonymous with VPC (one gateway per VPC) . The only reason we haven't changed it is to prevent breaking existing terraform deployments . There are a whole bunch of variables that we would like to rename ( We may do it at some point in the future)

We could certainly fix the re-apply because of the index order. Not sure if we will be changing the format.

**Comment by hotdawg789** [comment]
Understood. Thanks for information. 

since the tags afters deployment of the spoke gateways shouldnt change, i'll leverage 
```
 lifecycle {
    ignore_changes = [
      # Ignore changes to tags, e.g. because a management agent
      # updates these based on some ruleset managed elsewhere.
      tags,
    ]
  }
}
```

**Comment by arvindsree** [comment]
tag re-ordering issue should not be present in the latest version
