### ISSUE TITLE
Problem with aviatrix_vgw_conn

### ISSUE THREAD

**Issue by gregsteelxinja** [AviatrixSystems/terraform-provider-aviatrix#256]
This error is thrown after aviatrix_vgw_conn resource:

Error: couldn't find Aviatrix VGW Connection: Json Decode get_site2cloud_conn_detail failed: json: cannot unmarshal string into Go struct field ConnectionDetail.bgp_vgw_account of type []string

The resource is created okay and is in state as tainted

I think it might be because you try to load the bgp_vgw_account attribute as bgp_vgw_account_name?

	connectTransitGwToVgw.Add("bgp_vgw_account_name", vgwConn.BgpVGWAccount)

**Comment by inc1t3Ful** [comment]
Hi @gregsteelxinja , what Controller version are you on?

We are aware of this issue and have recently just released a minor patch (2.9.1) to fix this particular issue. This fix is for the latest Controller version 5.2.2122. If you have recently upgraded to this Controller version, simply source our new patch in the "providers" block in your Terraform file.

```
provider "aviatrix" {
   version = "2.9.1"
}
```

**Comment by gregsteelxinja** [comment]
Great thanks, yes we recently upgraded to 5.2.2122
