### ISSUE TITLE
Feature request: Enable Controller Security Group Management

### ISSUE THREAD

**Issue by Thamrius** [AviatrixSystems/terraform-provider-aviatrix#266]
Looking for the option to enable this option in the controller through terraform so that if a new apply is needed it does not remove the access.

**Comment by arvindsree** [comment]
Strictly speaking this isn't a resource in the terraform sense, it is more of a configuration/setting. 

We could possibly handle this in terraform(ref:8587), but we would recommend using something like 
[https://github.com/AviatrixSystems/Controller-HA-for-AWS ](Controller-HA) to handle this.

What do you mean by apply does not remove access? None of the resources in this provider affect security groups

**Comment by Thamrius** [comment]
> Strictly speaking this isn't a resource in the terraform sense, it is more of a configuration/setting.
> 
> We could possibly handle this in terraform(ref:8587), but we would recommend using something like
> [https://github.com/AviatrixSystems/Controller-HA-for-AWS](Controller-HA) to handle this.
> 
> What do you mean by apply does not remove access? None of the resources in this provider affect security groups

My controller was built utilizing terraform and upon running an apply to refresh data(during a support call) it removed the security group management settings.

**Comment by arvindsree** [comment]
There wouldn't be way to handle that this from this provider. The security group was built using the aws provider. It will show a diff since the controller modified it after gateways were launched. It is not possible to use the aviatrix terraform provider to handle something created outside the controller itself.

**Comment by Thamrius** [comment]
That does make sense, I will close this out. Thanks for the explanation.
