### ISSUE TITLE
Gateway creation error

### ISSUE THREAD

**Issue by dxciberaws** [AviatrixSystems/terraform-provider-aviatrix#309]
**Terraform versions:**

Terraform v0.12.21
+ provider.aviatrix v2.11.0
+ provider.aws v2.51.0

**Resource definition:**

resource "aviatrix_gateway" "sec-euc1" { 
  cloud_type = 1
  account_name = aviatrix_account.dxciber-sec.account_name
  gw_name = "sec-euc1"
  vpc_id = data.aws_cloudformation_stack.vpcStack-SEC.outputs["VPCId"]
  vpc_reg = data.aws_cloudformation_stack.vpcStack-SEC.outputs["AwsRegion"]
  gw_size = "t2.medium"
  subnet = data.aws_cloudformation_stack.vpcStack-SEC.outputs["AZASSLVPNCIDR"]
  vpn_access = true
  enable_elb = true
  split_tunnel = true
  vpn_cidr = "192.168.47.0/24"
  additional_cidrs = "172.24.0.0/16,172.31.0.0/16,172.30.0.0/21"
  max_vpn_conn = 100
}

**Error:**
[...]
aviatrix_gateway.sec-euc1: Still creating... [4m50s elapsed]

Error: failed to create Aviatrix gateway: Json Decode connect_container failed: EOF
 Body:

  on VPN-Gateway.tf line 1, in resource "aviatrix_gateway" "sec-euc1":
   1: resource "aviatrix_gateway" "sec-euc1" {

**Resulting resource status:**

Gateway is correctly created in Aviatrix controller but not updated in TF state. A "terraform import" command refreshes the state without error:

C:\Users\jalvarezferr.EAD\awslz\DXCIBER_SEC\solutions\sslvpn>terraform import aviatrix_gateway.sec-euc1 sec-euc1
var.controllerPwd
  Enter a value: g1l1p0Ll9s@

var.controllerUser
  Enter a value: jalvarezferr

aviatrix_gateway.sec-euc1: Importing from ID "sec-euc1"...
aviatrix_gateway.sec-euc1: Import prepared!
  Prepared aviatrix_gateway for import
aviatrix_gateway.sec-euc1: Refreshing state... [id=sec-euc1]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

A following "terraform plan" shows no changes are needed:

No changes. Infrastructure is up-to-date.

Error correscponds to the same issue reported at the Aviatrix Github: https://github.com/AviatrixSystems/terraform-provider-aviatrix/issues/15

In that case the error was related to the use of an https ELB in front of the controller, and was solved enabling http access to the controller through the then introduced controller_configuration resource.

**Comment by inc1t3Ful** [comment]
Hi @dxciberaws , for clarification, are you using an ELB in front of your controller? And if so, did the solution listed in the aforementioned Github issue resolve the problem?

AWS ELB does terminate the connection, which can explain the `Error: failed to create Aviatrix gateway: Json Decode connect_container failed: EOF
Body:`

Otherwise, could you please provide tracelogs by enabling debugging with TF_LOG=TRACE terraform apply and submit the output? Thanks
