### ISSUE TITLE
Allow supplying your own EIP arn when spinning up gateways

### ISSUE THREAD

**Issue by tkellen** [AviatrixSystems/terraform-provider-aviatrix#336]
Hi all!

First, thanks again for making a terraform provider for managing aviatrix resources, it's making a really big difference for our team. This request isn't specifically related to terraform, but this is the most direct path I know of to connecting with your team, so, hopefully this request is well received.

I'd like the ability to manage the EIP for gateways myself, in terraform, outside the lifecycle of things like `aviatrix_spoke_gateway` resources. The fact that this is handled entirely by the aviatrix controller on my behalf (and the EIP is destroyed if the gateway is destroyed) is non-optimal for numerous reasons I'd be happy to share if you don't see them immediately.

As a solution, I'm imagining that a new parameter could be added that allows the ARN of an EIP to be supplied when spinning up gateways, and that the controller's REST API would be modified to accept it and use it when present (defaulting to the existing behavior if that parameter is absent). Is this something that could be added to your roadmap? I'd be glad to implement support in the provider if so!

Looking forward to hearing your thoughts.

**Comment by inc1t3Ful** [comment]
Hi @tkellen !

Thank you so much! I hope we can continue to deliver and meet expectations :)

Thanks for bringing this to our attention! That is definitely a valid concern- I can file this as a feature request to the team and have it go from there. I will keep tabs and update you accordingly.

In the future, for non-Terraform (or Terraform haha) questions/concerns/feature requests, you may contact our support team through email : support@aviatrix.com . This will automatically file a ticket our team can track. Thanks again.

**Comment by inc1t3Ful** [comment]
Hi again! quick update.

Apologies, it seems I misread your concern. You can manage which EIP to use for your gateways (whether that be regular, spoke or transit), through the "allocate_new_eip" attribute. If set to false, you can specify an unallocated EIP in your pool to use on gateway creation using the "eip" attribute. If the gateway is to be deleted, the EIP will simply be returned to the pool without releasing it.

If "allocate_new_eip" is not set, by default will be true, and will allocate a new EIP for the gateway from AWS. And as you observed, if the gateway is removed, the EIP will be released.

Source: https://www.terraform.io/docs/providers/aviatrix/r/aviatrix_spoke_gateway.html#allocate_new_eip

**Comment by tkellen** [comment]
Oh my gosh, I don't know where the heck my head was when I wrote this but you're absolutely right. I'm sorry for the wasted time. Thank you once again!
