### ISSUE TITLE
Feature request: Create firewall security domains via Terraform

### ISSUE THREAD

**Issue by arvindsree** [AviatrixSystems/terraform-provider-aviatrix#36]
Created from https://github.com/AviatrixSystems/terraform-provider-aviatrix/issues/503 on behalf of @lctnstn
![image](https://user-images.githubusercontent.com/21178759/64663594-3cb40f80-d401-11e9-9bd4-6f40363b42f9.png)

**Comment by zhiqiangjin** [comment]
This issue has been solved.

**Comment by arvindsree** [comment]
Supported in provider version 2.6.0
