### ISSUE TITLE
Implement logging by level

### ISSUE THREAD

**Issue by DerkSchooltink** [AviatrixSystems/terraform-provider-aviatrix#364]
**Problem**

During an inspection of our logging I ran into sensitive data being logged, which I could trace back to this go-aviatrix package:

```
2020/04/02 01:00:30 [TRACE] POST https://<address>/v1/api Body: action=login&password=<redacted>&username=<redacted>
```
The login and password are logged plaintext, everyone that has access to the logging could use these credentials. 

The current logging implementation tags log lines with a `[LOG_LEVEL]` prepended to the message. This is cool from a visual aspect but this level can't be used by log aggregation tools to filter. So a message logged as TRACE isn't actually logged as trace, it just looks like a trace message.

**Proposed solution**

Using a third-party implementation for handling logs is widely accepted and offers more control over log levels. Using https://github.com/sirupsen/logrus for this, the log level is logged as a separate field, which can be picked up by log aggregation tools to filter out sensitive messages. 

Using `log.SetLevel(log.InfoLevel)` wil limit devoid the logging output from all TRACE and DEBUG messages. While trace logging can be useful while testing, using this approach developers can turn it off in production.

**Comment by arvindsree** [comment]
Wouldn't that be present only if you set the TF_LOG environment variable to TRACE?

**Comment by DerkSchooltink** [comment]
> Wouldn't that be should only if you set the TF_LOG environment variable to TRACE?

I think the TF_LOG you are referring to is separate from the go-aviatrix library. Perhaps I could have worded this more clearly. :) This is why the attached PR only modifies the logging for that library and not the actual terraform provider.

**Comment by arvindsree** [comment]
I see. Sounds good
