### ISSUE TITLE
Feature request: Designated Gateway

### ISSUE THREAD

**Issue by arvindsree** [AviatrixSystems/terraform-provider-aviatrix#37]
Created from https://github.com/AviatrixSystems/terraform-provider-aviatrix/issues/514 on behald of @lctnstn

![image](https://user-images.githubusercontent.com/21178759/64663686-771dac80-d401-11e9-8170-df4cd99d3a04.png)

**Comment by zhiqiangjin** [comment]
This feature has been implemented. Close it for now.
