### ISSUE TITLE
Feature Request: Aviatrix Gateway - Use VPC/VNet DNS Server

### ISSUE THREAD

**Issue by arvindsree** [AviatrixSystems/terraform-provider-aviatrix#38]
Created from https://github.com/AviatrixSystems/terraform-provider-aviatrix/issues/624 on behalf of @walkafwalka 

![image](https://user-images.githubusercontent.com/21178759/64663776-b4823a00-d401-11e9-8809-de8f0308031b.png)

**Comment by zhiqiangjin** [comment]
This feature has been implemented.

**Comment by arvindsree** [comment]
Supported in provider version 2.5.0
