### ISSUE TITLE
Feature Request: Geo VPN

### ISSUE THREAD

**Issue by arvindsree** [AviatrixSystems/terraform-provider-aviatrix#39]
Created from https://github.com/AviatrixSystems/terraform-provider-aviatrix/issues/644 on behalf of @walkafwalka 
![image](https://user-images.githubusercontent.com/21178759/64663822-ded3f780-d401-11e9-84b9-bdadf7688c55.png)

**Comment by zhiqiangjin** [comment]
This feature has been implemented. Close it for now.
