### ISSUE TITLE
Feature Request: Add argument aviatrix_firenet_vpc to aviatrix_vpc resource

### ISSUE THREAD

**Issue by nathanlctnstn** [AviatrixSystems/terraform-provider-aviatrix#409]
Current resource has an argument to specify if a VPC being created is an Aviatrix Transit VPC. The GUI supports the creation of both Aviatrix Transit VPCs and Aviatrix FireNet VPCs. Can this functionality be added to the aviatrix_vpc resource?

**Comment by zhiqiangjin** [comment]
This is fixed and will be in UserConnect-4.6 release.
#415
