### ISSUE TITLE
Error using provider

### ISSUE THREAD

**Issue by adrianmkng** [AviatrixSystems/terraform-provider-aviatrix#44]
I'm running into this error trying to use the provider.
```
Error: Error running plan: 1 error(s) occurred:

* provider.aviatrix: invalid character '<' looking for beginning of value

2018-10-02T10:57:04.167+1000 [DEBUG] plugin.terraform-provider-aviatrix: 2018/10/02 10:57:04 [ERR] plugin: plugin server: accept unix /tmp/plugin717675651: use of closed network connection

2018-10-02T10:57:04.169+1000 [DEBUG] plugin: plugin process exited: path=/home/age/.terraform.d/plugins/terraform-provider-aviatrix
[terragrunt] 2018/10/02 10:57:04 Hit multiple errors:
exit status 1
```

I followed the installation instructions to build compile the provider, although I'm not sure if this is the expected output.

```
$ make fmt
gofmt -w $(find . -name '*.go' |grep -v vendor)
$ make build
==> Checking that code complies with gofmt requirements...
go install
```

Here is the details of my system:
```
$ uname -a
Linux age-lm 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ terraform version
Terraform v0.11.8
+ provider.aviatrix (unversioned)

$ cat /etc/os-release 
NAME="Linux Mint"
VERSION="19 (Tara)"
ID=linuxmint
ID_LIKE=ubuntu
```

**Comment by adrianmkng** [comment]
I have a feeling that it might be to do with the MFA that's been enabled on Aviatrix. :(

**Comment by arvindsree** [comment]
Could you share your terraform tf template. Looks like there could be a typo.

**Comment by adrianmkng** [comment]
Just trying to run this for now:

```
resource "aviatrix_account" "acc" {
  account_name = "${var.org}-${var.environment}"
  cloud_type = 1
  aws_account_number = "${local.account_id}"
  aws_iam = "true"
  aws_role_app = "arn:aws:iam::${local.account_id}:role/aviatrix-role-app"
  aws_role_ec2 = "arn:aws:iam::${local.account_id}:role/aviatrix-role-ec2"
}
```

**Comment by arvindsree** [comment]
Seems to be fine (aws_role_app  and aws_role_ec2 are not required if using the defualt IAM role names). 

From the error message, it could be "<"  being present in the json REST API response from the controller. Are you using the latest controller version(3.4.771 (From the Help button on the top)? If not could you try upgrading to the latest (Settings->Maintenance->Upgrade to the latest)

**Comment by adrianmkng** [comment]
Thanks @arvindsree!
No, the version that I current have is: UserConnect-3.4.745. I'll try upgrading and see how I go.

**Comment by adrianmkng** [comment]
Ok I've updated the AviatrixController and I've remove 2FA and the provider is working properly now. Thanks for the help @arvindsree!

**Comment by arvindsree** [comment]
Which 2FA did you use? LDAP or Duo? and is this for the controller login or the gateway VPN?
