### ISSUE TITLE
New Accounts don't show in GW Create interface

### ISSUE THREAD

**Issue by jaferrando** [AviatrixSystems/terraform-provider-aviatrix#47]
Hi

1- Create a new account using the terraform provider
2- In the console go to create a new GW. The account does not show in the accounts list.
3- Edit the account properties, make no changes but save with "OK".
4- Now the account appears in the Create GW accounts list

Regards

**Comment by arvindsree** [comment]
This is cached in the browser. Fixing this would cause the gateway page to be a bit slower. Reloading the page would help

**Comment by arvindsree** [comment]
This issue is not specific to terraform provider itself. An internal issue has been filed to not require a hard reload of the page. Meanwhile, you can refresh the entire page to bypass this.

**Comment by arvindsree** [comment]
This has been fixed in the latest controller version 4.0.626. Navigate to accounts page and then visit gateway page for the changes to see the account
