### ISSUE TITLE
Feature Request: Add ability to manage vpn settings through terraform

### ISSUE THREAD

**Issue by slandry90** [AviatrixSystems/terraform-provider-aviatrix#472]
We are looking to manage VPN configuration settings via Terraform and are missing the ability to set the "idle timeout" and "renegotiation interval" values.

**Comment by inc1t3Ful** [comment]
Attaching ticket ID 17468 for reference.

Thank you for the request! Expected to be released with Aviatrix Terraform provider release R2.18

**Comment by inc1t3Ful** [comment]
#608 - for your reference.

This feature has been released on R2.17.1 yesterday.

Thanks again!
