### ISSUE TITLE
Support for High Availability for Gateways

### ISSUE THREAD

**Issue by davidschou** [AviatrixSystems/terraform-provider-aviatrix#5]
Currently you can also create a single Gateway with terraform code.  The HA option for Gateways are only available in the UI or api call.  

Note: if you terraform create a single Gateway and enable HA.  If you ever perform a failover, your terraform code will not match anymore.

**Comment by arvindsree** [comment]
@

**Comment by edumanig** [comment]
Hi David, 

The keyword to support gateway HA feature is "ha_subnet".   Please add this line to your gateway resource.

resource "aviatrix_gateway" "test_gateway_name" {
          ha_subnet = "10.10.0.0/24"
          ....
          ....
}
