### ISSUE TITLE
Cannot Peer Spoke to Aviatrix Transit Gateway in GUI

### ISSUE THREAD

**Issue by lctnstn** [AviatrixSystems/terraform-provider-aviatrix#501]
If an Aviatrix transit gateway is created via Terraform using `aviatrix_gateway` is does not show up as an available option to peer a spoke gateway to in the GUI.

**Comment by lctnstn** [comment]
Gateways created with Terraform are also not visible in the GUI for selection in the `Enable the Aviatrix Gateway for FireNet Function` (Firewall Network > Step 5).

**Comment by iggynopolis** [comment]
You can create Aviatrix transit gateways using the "aviatrix_transit_vpc" resource. Using the "aviatrix_gateway" resource will not create an Aviatrix transit gateway, but a regular Aviatrix gateway.

[link to aviatrix_transit_vpc resource documentation](https://github.com/AviatrixSystems/terraform-provider-aviatrix/blob/master/website/docs/r/aviatrix_transit_vpc.html.markdown)


You can attach a spoke gateway to a transit gateway within the "aviatrix_spoke_vpc" resource by setting the "transit_gw" attribute to the name of the transit gateway you want to attach to.

**Comment by lctnstn** [comment]
@iggynopolis 
1. This issue is specifically that if I create an Aviatrix Transit Gateway I cannot make a peering using the GUI-- it doesn't show up in dropdown menus.
2. I had opened a separate issue about the attachment, thank you!

**Comment by iggynopolis** [comment]
Are you trying to create the Aviatrix Transit Gateway in Terraform using the "aviatrix_gateway" resource? That resource will only create a regular Aviatrix gateway, not the transit gateway you need. Regular Aviatrix gateways won't show up in the dropdown menus for attaching spoke gateways to transit gateways or for the Firenet function.

You can only create an Aviatrix Transit Gateway in Terraform using the "aviatrix_transit_vpc" resource. After that, your transit gateway should be showing up in the dropdown menus in the GUI where a transit gateway is needed.

**Comment by lctnstn** [comment]
@iggynopolis - Dammit. That was it the whole time. I misunderstood the meaning of the module title `aviatrix_transit_vpc`. Thanks!

**Comment by arvindsree** [comment]
I agree. we are planning to rename the module to transit_gw in a future release
