### ISSUE TITLE
Feature request: Peer Spoke Gateway to Transit Gateway via Terraform

### ISSUE THREAD

**Issue by lctnstn** [AviatrixSystems/terraform-provider-aviatrix#502]
Request to add the ability to attach spoke gateways to transit gateway/nexthop gateway using Terraform.

**Comment by iggynopolis** [comment]
You can attach a spoke gateway to a transit gateway within the "aviatrix_spoke_vpc" resource by setting the "transit_gw" attribute to the name of the aviatrix transit gateway you want to attach to.

`# Set Aviatrix arm spoke_vpc
resource "aviatrix_spoke_vpc" "test_spoke_vpc_arm" {
  cloud_type   = 8
  account_name = "my-arm"
  gw_name      = "spoke-gw-01"
  vpc_id       = "spoke:test-spoke-gw-123"
  vpc_reg      = "West US"
  vpc_size     = "t2.micro"
  subnet       = "10.13.0.0/24"

  transit_gw = "test-transit-gw"
}`
