### ISSUE TITLE
Multiple gw_filter_tag_list blocks within aviatrix_fqdn resource behavior

### ISSUE THREAD

**Issue by MattSurabian** [AviatrixSystems/terraform-provider-aviatrix#510]
## Expected
When specifying an `aviatrix_fqdn` resource it is possible to attach it to a gateway using the `gw_filter_tag_list` block. Mutlplitles are allowed and in the case where a given spoke gateway is deployed in HA mode mutlple attachments can be made this way:

```
resource "aviatrix_fqdn" "main" {
  fqdn_tag     = "amazing-fabulous-allowlist"
  fqdn_enabled = true
  fqdn_mode    = "white"

  gw_filter_tag_list {
    gw_name = aviatrix_spoke_gateway.main.gw_name
  }

  # Need to attach to the hagw as well, this name isn't output by the spoke resource though
  gw_filter_tag_list {
    gw_name = "${aviatrix_spoke_gateway.main.gw_name}-hagw"
  }


  domain_names {
    fqdn  = "*wakawaka.com"
    proto = "tcp"
    port  = "443"
  }
.
.
.
}
```

Presumably many gateways could be attached in this way, not just individual gateways that happen to be deployed in ha mode. This works today:

```
      + gw_filter_tag_list {
          + gw_name = "abg-us-east-1-spoke-p-geneva-aviatrix-ubuntu"
        }
      + gw_filter_tag_list {
          + gw_name = "abg-us-east-1-spoke-p-geneva-aviatrix-ubuntu-hagw"
        }
```

**In the case where many are attached it's expected that removing any single one would detach that gateway from the fqdn egress list.**  

## Actual
 While the attachments work well the behavior on removal is a bit sketchy:

**In the case where ALL are removed from the terraform only the "first" one appears in the diff**
```    
        - gw_filter_tag_list {
          - gw_name        = "my-very-classy-gateway-aviatrix-ubuntu" -> null
          - source_ip_list = [] -> null
        }
```
**In the case where ANY except the first one is removed, the diff is empty and nothing is detached**

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**In the case where the FIRST ONE is removed, the first one shows in the diff and is the only one removed**
```     
        - gw_filter_tag_list {
          - gw_name        = "my-very-classy-gateway-aviatrix-ubuntu" -> null
          - source_ip_list = [] -> null
        }
```

Behavior in all cases is that while multiple gateways may be attached, removal only ever affects the first `gw_filter_Tag_list` block. This is reflected both in the diff and within Aviatrix.

### Versions:
User connect:

```UserConnect-6.0.2387```

Providers:
```
Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "aviatrix" (terraform-providers/aviatrix) 2.15.1...
- Downloading plugin for provider "aws" (hashicorp/aws) 3.0.0...

```

**Comment by inc1t3Ful** [comment]
Hi Matt!

Thank you for all the details! I was unable to reproduce your issues as described on provider 2.16+ and Controller 6.1+.

However, the FQDN feature automatically attaches to the HAGW if attached to the primary gateway as specified in the `gw_filter_tag_list {}` , so there is no need to specify the HAGW in a separate block. We can definitely add a note in the documentation for clarification.

This might explain the strange behavior when attempting to remove.

As an aside, `ha_gw_name` can be referenced from the spoke resource as of provider 2.14+.

**Comment by CyrusJavan** [comment]
I’m closing this issue because it has been inactive for many months.

Please reopen if you still encounter this issue with the latest version [v2.18.2](https://github.com/AviatrixSystems/terraform-provider-aviatrix/releases/tag/v2.18.2).

Thank you!
