### ISSUE TITLE
Feature Request: Add security_domain Terraform resource

### ISSUE THREAD

**Issue by dix-icomys** [AviatrixSystems/terraform-provider-aviatrix#556]
We are looking to have a standalone SecurityDomain resource in addition to in-line `security_domains ` definitions in the `aviatrix_aws_tgw ` resource.

Similar to `aws_security_group_rule` and `aws_security_group`, where we can define the rules outside of the main SG object

**Comment by shuoliugit** [comment]
Hi @dix-icomys, 
The standalone resource `aviatrix_aws_tgw_security_domain` will be added in the upcoming R2.19.0 release.

**Comment by inc1t3Ful** [comment]
#855 
#879 

R2.19.0 has been released:
https://registry.terraform.io/providers/AviatrixSystems/aviatrix/latest/docs/guides/release-notes#2190
