### ISSUE TITLE
Feature Request: Global Accelerator option for Transit Gateway VPNs

### ISSUE THREAD

**Issue by komalthecoolk** [AviatrixSystems/terraform-provider-aviatrix#604]
**Is your feature request related to a problem? Please describe.**
We are trying to deploy a VPN on a TransitGateway managed by Aviatrix controller with the Global Accelerator option (which is available on the controller under the TGW Orchestrator). This argument isn't available in the `aviatrix_aws_tgw_vpn_conn` resource.

**Describe the solution you'd like**
An option to add a yes/no or True/False flags for the Global Accelerator for VPN would be helpful.

**Comment by CyrusJavan** [comment]
Hi @komalthecoolk,
Thanks for this suggestion! I've opened an issue on our internal issue tracker and we will get this feature added in a future release. Thanks!
