### ISSUE TITLE
aviatrix_firewall_instance does not deploy as per the config

### ISSUE THREAD

**Issue by Danny-Cooke** [AviatrixSystems/terraform-provider-aviatrix#611]
**Describe the problem**

aviatrix_firewall_instance does not deploy as per the configuration in terraform 

**To Reproduce**

we define the firewall instance as per -
```
resource "aviatrix_firewall_instance" "test_firewall_instance1" {
  vpc_id                                 = aviatrix_vpc.aws_vpc.vpc_id
  firenet_gw_name                = aviatrix_transit_gateway.test_transit_gateway_aws.gw_name
  firewall_name                     = "avx-firewall-instance"
  firewall_image                    = "Fortinet FortiGate (BYOL) Next-Generation Firewall"
  firewall_size                        = "c5n.large"
  management_subnet         = "10.100.0.80/28"
  egress_subnet                    = "10.100.0.96/28"
}
```
The value specified for the management subnet seems to be ignored. It instead deploys to the same subnet as egress subnet. 

so we specify -
  management_subnet         = "10.100.0.80/28"
  egress_subnet                    = "10.100.0.96/28"
and what gets deployed is by terraform is-
  management_subnet         = "10.100.0.96/28"
  egress_subnet                    = "10.100.0.96/28"

**Expected behavior**
We expect it to deploy as per our requirements. 

**Additional data / screenshots**
Include any relevant tf files.

**Environment:**
 - Provider version 2.17
 - Terraform version 0.13

**Additional context**
one of the main issues here is although incorrect, it does still create the resource. Unfortunately if we run terraform apply again is decides there has been config drift and tries to destroy the resource.

**Comment by inc1t3Ful** [comment]
Hi Danny! Thank you for reporting this issue.

This is definitely a bug on the provider- the behavior can be explained in the following documentation [here](https://docs.aviatrix.com/HowTos/firewall_network_workflow.html#fortigate-specifications).

In short, Fortinet firewall instances do not require a `management_subnet`, which can be seen on the Controller GUI. `management_subnet` should only be required for Palo Alto Firewalls. Fortinet instances have 2 interfaces, eth0 and eth1, none of which are to be created in the VPC's "management_subnets". Both those interfaces will be created in the same subnet as specified by the `egress_subnet` attribute.

I will file a ticket for our team to fix this issue on the provider. In the meanwhile, to workaround this issue, after creating the resource, please set a lifecycle block in the firewall instance resource as follows, to ignore the deltas found in the state. For more information on lifecycle, please see the following Hashicorp doc [here](https://www.terraform.io/docs/configuration/resources.html#lifecycle-lifecycle-customizations).
```
resource "aviatrix_firewall_instance" "test_firewall_instance1" {

   ...

   lifecycle { 
      ignore_changes  = [management_subnet]
   }
}
```

**Comment by Danny-Cooke** [comment]
thanks, i'll give this a Wiz today and feedback.

**Comment by inc1t3Ful** [comment]
#617 - fix for Github issue 611

Issue has been fixed, and release of R2.17.1 with other features and bug fixes will be available sometime next week.

**Comment by inc1t3Ful** [comment]
R2.17.1 has been released as of today! :)
