### ISSUE TITLE
Bug: Modifying VPN configuration of multiple gateways behind a load balancer fails

### ISSUE THREAD

**Issue by walkafwalka** [AviatrixSystems/terraform-provider-aviatrix#623]
If you have multiple gateways behind a load balancer, modifying the VPN configuration of one of the gateways modifies the VPN configuration of all of the gateways.

This is desired. However, Terraform attempts to modify the VPN configuration for every gateway which causes an error for every modification after the first gateway since the configuration is already up-to-date: `Error: failed to modify split tunnel: Rest API modify_split_tunnel(modify) Get failed: [Aviatrix Error] Nothing to modify. Aborting (If this is not clear, go to docs.aviatrix.com and search the matching error string for resolution.)`

In the following example, if you change `split_tunnel` from `true` to `false`, you will receive the error stated above:
```
resource "aviatrix_gateway" "gateway" {
  count = 2
  ...
  gw_name = "gateway-${count.index}"
  ...
  vpn_access   = true
  enable_elb   = true
  elb_name     = "vpn-elb"
  split_tunnel = true
  ...

}
```

**Comment by arvindsree** [comment]
Yes. That is the current design. Every gateway under a load balancer must have identical configuration.

If you wish to have different configurations, you need to have ELB disabled.

We could probably ignore the error however

**Comment by walkafwalka** [comment]
@arvindsree, I figured so this is low priority since the apply actually works. You would be willing to accept a PR for ignoring the "Nothing to modify" error?

Another possible solution would be to create a User VPN resource. For example:
```
resource "aviatrix_gateway" "gateway" {
  count = 2
  ...
  gw_name = "gateway-${count.index}"
  ...
  enable_elb = true
  elb_name   = aviatrix_gateway_elb.gateway_elb.name
  ...
}

resources "aviatrix_gateway_elb" "gateway_elb" {
  name         = "vpn-elb"
  vpn_access   = true
  split_tunnel = true
}
```
I am not familiar with the Aviatrix API but I do not think this is currently possible so ignoring the error would be the easier solution. You would have to be able to create and manage an ELB without having an associated gateway.

**Comment by arvindsree** [comment]
Yes, the error needs to be ignored whatsoever.

What you suggested would have been a nice way to go about the ELB. But in the current design, the ELB is coupled with the gateway. It gets created automatically with the first VPN gateway and is destroyed when the last gateway under the ELB is destroyed or the last VPN user to the ELB is destroyed/detached.

**Comment by walkafwalka** [comment]
Currently we are check if the `APIResp` returns true or false, and if false, we are return the reason as an error. See [goaviatrix/split_tunnel.go#L87](https://github.com/AviatrixSystems/terraform-provider-aviatrix/blob/master/goaviatrix/split_tunnel.go#L87).

Adding logic here to ignore the "Nothing to modify" reason works.

Before I submit a PR, do you think it would be better if the API responded with the typical success response describe [here](https://api.aviatrix.com/?version=latest#fbaed42f-cba5-4b3b-99f2-674849c282c8) even if there is nothing to modify?

**Comment by arvindsree** [comment]
You can submit the PR.

The API does not need to really have to reply with a failure(It is a grey area in my opinion, since it actually did not do anything)

**Comment by walkafwalka** [comment]
Thanks @zhiqiangjin. Beat me to it.
