### ISSUE TITLE
Feature Request: Aviatrix Gateway - Use VPC/VNet DNS Server

### ISSUE THREAD

**Issue by walkafwalka** [AviatrixSystems/terraform-provider-aviatrix#624]
https://docs.aviatrix.com/HowTos/gateway.html#use-vpc-vnet-dns-server

**Comment by arvindsree** [comment]
Moved to https://github.com/terraform-providers/terraform-provider-aviatrix/issues/38

**Comment by arvindsree** [comment]
Fixed in https://github.com/terraform-providers/terraform-provider-aviatrix/pull/81 in provider version 2.5.0
