### ISSUE TITLE
Can't attach fqdn filter tag list to spoke gateway 

### ISSUE THREAD

**Issue by MattSurabian** [AviatrixSystems/terraform-provider-aviatrix#63]
**Plugin Version:** 2.3.36
 **Controller Version:** UserConnect-5.0.2773

Looks like there isn't a way to attach an alredy existing FQDN tag list to a spoke gateway. The provider seems to always attempt creation of the tag which fails with this error:

```
Error: failed to create Aviatrix FQDN: Rest API add_fqdn_filter_tag Get failed: [Aviatrix Error] entry my_redacted_tagname already exists (If this is not clear, go to docs.aviatrix.com and search the matching error string for resolution.)
```

TF:
```
resource "aviatrix_fqdn" "main" {
    fqdn_tag     = "my_already_created_redacted_tagname"
    fqdn_enabled = false
    fqdn_mode    = "white"

    gw_filter_tag_list {
        gw_name        = aviatrix_spoke_gateway.main.gw_name
    }
}

```

I would expect this connection to work even though the tag already exists. It's also possible there's another way to do this and I'm bad at reading docs :-(

TFSTATE:
```
{
  "version": 4,
  "terraform_version": "0.12.8",
  "serial": 2,
  "lineage": "f4069111-e7b1-a027-3cad-af879fdbb8dc",
  "outputs": {},
  "resources": [
    {REDACTED},      
    {
      "mode": "managed",
      "type": "aviatrix_spoke_gateway",
      "name": "main",
      "provider": "provider.aviatrix",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "account_name": "REDACTED",
            "allocate_new_eip": true,
            "cloud_instance_id": "REDACTED",
            "cloud_type": 1,
            "eip": "REDACTED",
            "enable_active_mesh": true,
            "enable_snat": false,
            "gw_name": "REDACTED",
            "gw_size": "c5.large",
            "ha_eip": "REDACTED",
            "ha_gw_size": "c5.large",
            "ha_insane_mode_az": "",
            "ha_subnet": "REDACTED",
            "ha_zone": "",
            "id": "REDACTED",
            "insane_mode": false,
            "insane_mode_az": "",
            "single_az_ha": false,
            "subnet": "REDACTED",
            "tag_list": [REDACTED],
            "transit_gw": "REDACTED",
            "vpc_id": "REDACTED",
            "vpc_reg": "us-east-1"
          },
          "private": "REDACTED"
        }
      ]
    }
  ]
}
```

**Comment by MattSurabian** [comment]
Maybe this would be solved by a new resource that's just for associating existing tag lists with a gateway.

**Comment by arvindsree** [comment]
If the resource is already created, you need to import it into the state

https://www.terraform.io/docs/import/index.html

https://www.terraform.io/docs/providers/aviatrix/r/aviatrix_fqdn.html#import

**Comment by arvindsree** [comment]
In your case it would be 
terraform import aviatrix_fqdn.main my_already_created_redacted_tagname

**Comment by MattSurabian** [comment]
That makes sense, so if we were to import it we could then add various filters onto it from there. 

In our case the tag is managed by another team so we were hoping to just be able to associate filters. Maybe that's an API level limitation?

**Comment by MattSurabian** [comment]
^^ Ultimately the reason we want that is so we could run a `terraform destroy` and not destroy things that are at least partially the purview of another team.

**Comment by arvindsree** [comment]
Its not an API limitation, it is the design of terraform itself on how resources are managed.

If you don't want to delete the tag you could just remove it from state by 
terraform state rm aviatrix_fqdn.main

**Comment by arvindsree** [comment]
You might also want to look at terraform teams/organizations on managing state across multiple teams

**Comment by MattSurabian** [comment]
Thanks, they're not using terraform otherwise we'd be set on using their state file. Not a big deal as we are now just using an additional tag that we completely control both the tag and the filter lists that are attached to it.

I think the distinction on the API I was making was that if I wanted to associate an existing fqdn tag that wasn't created in terraform with a spoke gateway that was created in terraform is that possible? Seems like I can't specify an fqdn tag when creating the spoke gateway, nor can I associate the spoke gateway with an existing fqdn tag unless it was created in terraform as well.

**Comment by MattSurabian** [comment]
I guess to your point I could just import it. But yeah, would be nice to be able to just delete the association of the fqdn tag with the spoke gateway and not the tag itself if possible. Anyway happy to  close.
