### ISSUE TITLE
Feature Request: Destination Nat

### ISSUE THREAD

**Issue by arvindsree** [AviatrixSystems/terraform-provider-aviatrix#64]
![image](https://user-images.githubusercontent.com/21178759/65626449-4ea9bc80-df82-11e9-810e-465dbf940cde.png)

Created from https://github.com/AviatrixSystems/terraform-provider-aviatrix/issues/646 on behalf of @jbruett

**Comment by zhiqiangjin** [comment]
This feature has been implemented. Close it for now.
