### ISSUE TITLE
Terrform plan still shows the aws instances related to gateway after previous successful apply

### ISSUE THREAD

**Issue by infa-apatel** [AviatrixSystems/terraform-provider-aviatrix#647]
My **terrform apply** that creates the primary and backup gateways with elb and site2cloud tunnel runs without any problem. 

 But, right after the apply is complete successfully, if I re-run terraform plan it wants to again create the **_aws_instance_** related to backup and primary aviatrix gateway.  It also wants to create aws_lb. It also wants to recreate the site2cloud tunnel. 

For aws_instance and aws_lb, it shows that its adding all the attribuates all over again.  For site2cloud, it shows it is recreating because the backup_gateway_name name :

 module.vpn.aviatrix_site2cloud.aviatrix_vpn_sitetocloud_tunnel[0] will be updated in-place
  ~ resource "aviatrix_site2cloud" "aviatrix_vpn_sitetocloud_tunnel" {
      + backup_gateway_name        = "<GATEWAY_NAME>"
        connection_name            = "<tunnel_NAME>"
        connection_type            = "unmapped"
        custom_algorithms          = false
        enable_dead_peer_detection = true
        ha_enabled                 = true

I did not change anything between running terrform apply and terraform plan .

**Comment by infa-apatel** [comment]
The aws_instance it is trying to recreate has plan that looks like this:

 <= data "aws_instance" "gateway_instance"  {
      + ami                         = (known after apply)
      + arn                         = (known after apply)
      + associate_public_ip_address = (known after apply)
      + availability_zone           = (known after apply)
      + credit_specification        = (known after apply)
      + disable_api_termination     = (known after apply)
      + ebs_block_device            = (known after apply)
      + ebs_optimized               = (known after apply)
      + ephemeral_block_device      = (known after apply)
      + host_id                     = (known after apply)
      + iam_instance_profile        = (known after apply)
      + id                          = (known after apply)
      + instance_state              = (known after apply)
      + instance_tags               = (known after apply)
      + instance_type               = (known after apply)
      + key_name                    = (known after apply)
      + monitoring                  = (known after apply)
      + network_interface_id        = (known after apply)
      + password_data               = (known after apply)
      + placement_group             = (known after apply)
      + private_dns                 = (known after apply)
      + private_ip                  = (known after apply)
      + public_dns                  = (known after apply)
      + public_ip                   = (known after apply)
      + root_block_device           = (known after apply)
      + security_groups             = (known after apply)
      + source_dest_check           = (known after apply)
      + subnet_id                   = (known after apply)
      + tags                        = (known after apply)
      + tenancy                     = (known after apply)
      + user_data                   = (known after apply)
      + user_data_base64            = (known after apply)
      + vpc_security_group_ids      = (known after apply)

**Comment by arvindsree** [comment]
Moved here https://github.com/terraform-providers/terraform-provider-aviatrix/issues/167
