### ISSUE TITLE
Provider cannot get argument values from remote state

### ISSUE THREAD

**Issue by enummela** [AviatrixSystems/terraform-provider-aviatrix#648]
The Aviatrix Terraform provider seems incapable of getting argument values from remote state (I am using S3 as my Terraform backend).

Using the example configuration below, `terraform apply` attempts to create the account without success until it eventually times out.

```
provider "aviatrix" {
  controller_ip           = data.terraform_remote_state.infrastructure.outputs.controller_public_ip
  username                = "admin"
  password                = data.aws_ssm_parameter.aviatrix_password.value
  skip_version_validation = false
}

resource "aviatrix_account" "myaccount" {
  account_name       = "myaccount"
  aws_account_number = data.aws_caller_identity.current.account_id
  aws_iam            = true
  aws_role_app       = data.terraform_remote_state.infrastructure.outputs.app_role_arn
  aws_role_ec2       = data.terraform_remote_state.infrastructure.outputs.ec2_role_arn
  cloud_type         = 1
}
```

If I create the Aviatrix account manually in the controller and run `terraform import aviatrix_account.myaccount myaccount` then an error message will complain that the `controller_ip` argument does not have a value.

The only work around I have found is to comment all of the Aviatrix provider resources, run `terraform apply` so that the remote state data source is pulled into local state, uncomment the Aviatrix provider resources, and run `terraform apply` again.

**Comment by arvindsree** [comment]
This repo has migrated to https://github.com/terraform-providers/terraform-provider-aviatrix/ . Please submit the issue there for visibility
