### ISSUE TITLE
Please provide the public_ip address as a terraform output for the aviatrix_gateway resource

### ISSUE THREAD

**Issue by davidschou** [AviatrixSystems/terraform-provider-aviatrix#7]
Can you please add the public_ip of a gateway as an output so it can be consumed?  

```
resource "aviatrix_gateway" "test_gw_us_west_1" {
  cloud_type   = 1
...
...
...
}
```

I'd like to reference it like:
```
${aviatrix_gateway.test_gw_us_west_1.public_ip}
```

The usage is if I have a Controller that is **not** open to 0.0.0.0/0.  So when I create a new Gateway, I'd like to add it to the ingress to the Controller SG.

**Comment by jorgebonilla** [comment]
My colleague just submitted a Pull Request for this feature. (https://github.com/AviatrixSystems/terraform-provider-aviatrix/pull/8). We'll test it out before it is merged but "coming sooner than you think" is my point.

**Comment by rakesh568** [comment]
Fixed with commit https://github.com/AviatrixSystems/terraform-provider-aviatrix/commit/bbffd6a04412fc5f07db9b77ea6555d226226c2b.
