### ISSUE TITLE
saml_endpoint for creating VPN user through terraform

### ISSUE THREAD

**Issue by infa-apatel** [AviatrixSystems/terraform-provider-aviatrix#70]
Hi 

We are using terraform to create VPN users and we use saml .  I am able to specify the LB name, but it fails saying "This Gateway/Loadbalancer has SAML enabled but no Endpoint was provided for the user add"

Any plan on bringing support for saml endpoint for terraform for create vpn user? we do a lot of this in our environment and it would amazing if you guys can have this support.

**Comment by arvindsree** [comment]
Its being addressed in this https://github.com/AviatrixSystems/terraform-provider-aviatrix/pull/69

**Comment by infa-apatel** [comment]
Thanks Arvindsree! do we know the timeline when this will be available?  We are releasing our hosted platform this week, where we would like to see the VPN user creation automation.
