### ISSUE TITLE
elb_name is not avaiable for creating aviatrix gateway in terrform

### ISSUE THREAD

**Issue by infa-apatel** [AviatrixSystems/terraform-provider-aviatrix#72]
We are using automation to create our clients environments with aviatrix gateway, tunnel, and vpn_users.  For creating VPN user, we need ELB name, which we are neither able to specify during creation of gateway in terraform, nor can we retrieve it any way.  We just got the fix for saml_endpoint, but now we are stuck because we don't have a way to specify/retrieve the elb name.

**Comment by arvindsree** [comment]
Unfortunately the list_vpcs_summary REST API only returns elb_dns_name currently so this cannot be returned.  
The only option is to pass this as a parameter while calling the "create_container" API
So this would become an input parameter rather than output. 

A work around is to use to disable ELB. This way gw_name itself can be used for the VPN users

**Comment by arvindsree** [comment]
Hi there,

elb_name input has been added

Please try the add users after about 10 secs after the gateway is created. You can use the local-exec provisioner as shown below to automate if required

resource "aviatrix_gateway" "vpn-gateway-test" {
  cloud_type   = 1
  account_name = "aws"
  gw_name      = "gw1"
  vpc_id       = "vpc-xxxxxxx"
  vpc_reg      = "us-east-2"
  vpc_size     = "t2.micro"
  vpn_access   = "yes"
  saml_enabled = "yes"
  cidr         = "192.168.43.0/24"
  enable_elb   = "yes"
  elb_name     = "elb1"
  split_tunnel = "yes"
  vpc_net      = "172.31.0.0/20"


  provisioner "local-exec" {
    command = "sleep 10"
  }
}

resource "aviatrix_vpn_user" "user1" {
  vpc_id = "vpc-xxxxxx"
  gw_name = "${aviatrix_gateway.vpn-gateway-test.elb_name}"
  user_name = "user1"
  saml_endpoint ="endpoint1"
}


Thanks,
Arvind

**Comment by arvindsree** [comment]
Let us know if this will work for you . Else, please re-open

**Comment by infa-apatel** [comment]
Thanks Arvindsree! it worked perfectly!
