### ISSUE TITLE
Terraform apply error when creating gateway, " Failed to create peering HA: Peer HA is not supported on VPN gateway"

### ISSUE THREAD

**Issue by infa-apatel** [AviatrixSystems/terraform-provider-aviatrix#78]
Hi Team, 

We are trying to create aviatrix gateway using terraform.  We also are trying to create HA peering gateway by specifying public_subnet and zone values.  You documentation says that this should be supported.  But, when I apply the changes I get an error:

 **Failed to create peering HA: Peer HA is not supported on VPN gateway"

Error: Error applying plan:

1 error(s) occurred:

* module.vpc.aviatrix_gateway.aviatrix_vpn_gateway: 1 error(s) occurred:

* aviatrix_gateway.aviatrix_vpn_gateway: Failed to create peering HA: Peer HA is not supported on VPN gateway**

Here are the values we are passing:

**module.vpc.aviatrix_gateway.aviatrix_vpn_gateway: Creating...
  account_name:                "" => "<ACCOUNT_NAME>"
  backup_public_ip:            "" => "<computed>"
  cidr:                        "" => "192.168.43.0/24"
  cloud_instance_id:           "" => "<computed>"
  cloud_type:                  "" => "1"
  cloudn_bkup_gateway_inst_id: "" => "<computed>"
  elb_name:                    "" => "<ELB_NAME>"
  enable_elb:                  "" => "yes"
  gw_name:                     "" => "<GATE_WAY_NAME>"
  public_dns_server:           "" => "<computed>"
  public_ip:                   "" => "<computed>"
  public_subnet:               "" => "<SUBNET_INFO_FOR_ZONE_B>"
  saml_enabled:                "" => "yes"
  security_group_id:           "" => "<computed>"
  split_tunnel:                "" => "yes"
  vpc_id:                      "" => "<VPC_ID>"
  vpc_net:                     "" => "<SUBNET_INFO_FOR_ZONE_A>"
  vpc_reg:                     "" => "us-west-2"
  vpc_size:                    "" => "t2.micro"
  vpn_access:                  "" => "yes"
  zone:                        "" => "aws_subnet.public_b.availability_zone"**

**Comment by infa-apatel** [comment]
NOTE:  There is also one more bug:

1) If you update an existing gateway that with public_subnet and zone, it doesn't create the HA peering gateway.  But it does end up updating the information related to public_subnet and zone for the existing gateway. 

2) now when you run terraform destory, it will fail trying to delete the peering gateway which it never created.. but, it thinks that it has a gateway because the update was successful in updating the public subnet and zone info.

**Comment by arvindsree** [comment]
The error message is valid. You need to create a seperate non-VPN gateway if you want peering HA

Updating public subnet and zone is not supported. You have to destroy first and launch a new gateway in the desired subnet

**Comment by infa-apatel** [comment]
Thanks Arvindsree for your prompt response as always! 

I am not quite understanding you suggestion.  Can you show me a terraform example how you would do this?  How do I create a seperate non-VPN gateway and associate it with aviatrix VPN gateway so they can backup each other in case a zone goes down.

**Comment by arvindsree** [comment]
The new gateway has to be in the same vpc as the VPN gateway that you wish to peer. Please note that terraform provider does not support setting the additional CIDR in the split tunnel, as of now. In the following example, you will have to add 10.0.0.0/24 to the VPN split tunnel additional CIDR manually after the VPN  gateway is created

resource "aviatrix_gateway" "peer_gw1" {
  cloud_type = 1
  account_name = "aws"
  gw_name = "avtxgw1"
  vpc_id = "vpc-zzzzzzz"
  vpc_reg = "us-east-1"
  vpc_size = "t2.micro"
  vpc_net = "172.31.0.0/20"
  public_subnet="172.31.16.0/20"
}


resource "aviatrix_gateway" "peer_gw2" {
  cloud_type = 1
  account_name = "aws"
  gw_name = "avtxgw2"
  vpc_id = "vpc-yyyyy"
  vpc_reg = "eu-central-1"
  vpc_size = "t2.micro"
  vpc_net = "10.0.0.0/24"
  public_subnet = "10.0.1.0/24"
}

resource "aviatrix_gateway" "vpn_gw" {
  cloud_type = 1
  account_name = "aws"
  gw_name = "vpngw"
  vpc_id = "${aviatrix_gateway.peer_gw1.vpc_id}"
  vpc_reg = "${aviatrix_gateway.peer_gw1.vpc_reg}"
  vpc_size = "t2.micro"
  vpc_net = "${aviatrix_gateway.peer_gw1.vpc_net}"


  vpn_access = "yes"
  saml_enabled = "yes"
  cidr = "192.168.43.0/24"
  enable_elb = "yes"
  elb_name = "elb1"
  split_tunnel = "yes"

}

resource "aviatrix_tunnel" "test_tunnel1" {
  vpc_name1 = "${aviatrix_gateway.peer_gw1.gw_name}"
  vpc_name2 = "${aviatrix_gateway.peer_gw2.gw_name}"
}
~
~
~
~

**Comment by infa-apatel** [comment]
This is a bit different than what we had in mind.  For us VPN gateway is sitting in zone A.  We want another VPN gateway to sit in zone B for HA purpose.  These two gatewayss will have tunnels interfacing with our customer network usgin site2cloud. 

How do I setup two VPN gateways as HA?

**Comment by arvindsree** [comment]
VPN does not have HA. We have ELB's to load balance the traffic instead. 

You could have a secondary gateway for site2cloud HA for your use case.

![image](https://user-images.githubusercontent.com/21178759/47968277-86cba800-e01c-11e8-9f15-8c5ad958740a.png)

**Comment by infa-apatel** [comment]
Ok, I think now we are on the same page. Thanks for the diagram. The ELB that you are metioning is the TCP AWS loadbalancer.  This will load balance the VPN traffic.  But, what about the site to cloud traffic?  

1) Your document says this can be done through UDP load balancing.  Is there terraform for configuring udp load balancer.  If yes, where can I find an example of this terraform code?

2) For TCP AWS load balancer, do I specify same ELB name for the two VPN gateways I created? Will that automatically add the two VPN gatways under same ELB?

**Comment by arvindsree** [comment]
Correct. ELB is the TCP network load balancer  that is created when "enable_elb" is "yes" (Currently only one ELB is supported per VPC. This is automatically created/destroyed with the gateway)

Site2 cloud traffic does not go through ELB. ELB only forwards VPN traffic. 
Only one of the site2cloud links will be active at a time. When the active site2cloud link goes down, the HA site2cloud link should come up.

1. Unfortunately, there is no terraform for UDP load balancer yet. UDP load balancer is not necessary for this. It can be done through TCP ELB itself.
2. Correct. The same ELB name should be specified for the gateways to be under the same ELB. (They have to be in the same VPC as well)

**Comment by infa-apatel** [comment]
"Only one of the site2cloud links will be active at a time. When the active site2cloud link goes down, the HA site2cloud link should come up."  Does this happen automatically, or I have to write script for this to happen?

1. Site2Cloud for us uses UDP.  How do you use ELB load balancer for UDP traffic? 
2.  Make sense and clear, thanks!

**Comment by arvindsree** [comment]
It should happen automatically
1.  Site2cloud and ELB are for different services and on separate data paths. Site2cloud on the gateway and forwards traffic from the on premise network to the VPC. VPN service is on a different port and forwards traffic from the ELB(originally from VPN users) to the VPC. You cannot use ELB for UDP traffic.

**Comment by infa-apatel** [comment]
ok, I believe I understand all of it now :) Here is the code I am going to use.  Please confirm it this make sense.  

1) One primary VPN gateway in Zone A
2) One backup VPN gateway in Zone B
3) One siteToCloud, which is HA enabled, with two gateways, Primary and backup.  

resource "aviatrix_gateway" "aviatrix_vpn_primary_gateway" {
  cloud_type = 1
  account_name =  "<ACCOUNT_NAME>"
  gw_name = "<PRIMARY_GATE_WAY_NAME>"
  vpc_id = "<VPC_ID>"
  vpc_reg = "us-west-2"
  vpc_size = "t2.micro"
  vpc_net = "<SUBNET_INFO_FOR_ZONE_A>"
  cidr = "192.168.43.0/24"
  split_tunnel = "yes"
  enable_elb = "yes"
  elb_name= "<ELB_NAME>"
  vpn_access = "yes"
  saml_enabled = "yes"
}

resource "aviatrix_gateway" "aviatrix_vpn_backup_gateway" {
  cloud_type = 1
  account_name =  "<ACCOUNT_NAME>"
  gw_name = "<BACKUP_GATE_WAY_NAME>"
  vpc_id = "<VPC_ID>"
  vpc_reg = "us-west-2"
  vpc_size = "t2.micro"
  vpc_net = "<SUBNET_INFO_FOR_ZONE_B>"
  cidr = "192.168.43.0/24"
  split_tunnel = "yes"
  enable_elb = "yes"
  elb_name= "<ELB_NAME_SAME_AS_PRIMARY_GATEWAY>"
  vpn_access = "yes"
  saml_enabled = "yes"
}

resource "aviatrix_site2cloud" "aviatrix_vpn_sitetocloud_tunnel" {
  vpc_id = "<VPC_ID>"
  connection_name = "<CONNECTION_NAME>"
  remote_gateway_type = "generic"
  tunnel_type = "udp"
  primary_cloud_gateway_name = "<PRIMARY_GATE_WAY_NAME>"
  backup_gateway_name = "<BACKUP_GATE_WAY_NAME>"
  remote_gateway_ip = "<REMOTE_GATEWAY_IP>"
  remote_subnet_cidr = "<LIST_OF_REMOTE_CIDRs>"
  local_subnet_cidr = "<LOCAL_CIDR>"
  ha_enabled = "yes"
}

**Comment by arvindsree** [comment]
Looks good. Let us know if you run into any issues

**Comment by arvindsree** [comment]
Closing this for now as peering HA is not going to be supported on VPN

**Comment by infa-apatel** [comment]
Thanks Avrindsree. We have used the non-prod setup in our prod and so far the terraform side has no issues.  Prod side will take some time.  Will let you know how it goes.  Thanks for your help with this issue.
