### ISSUE TITLE
Support for terraform 0.14

### ISSUE THREAD

**Issue by mykter** [AviatrixSystems/terraform-provider-aviatrix#860]
**Describe the solution you'd like**
Clarity on whether 0.14 is currently supported - the README uses "v0.13+" a lot, implying it is, but the individual releases explicitly list "Supported Terraform version: v0.12.x and v0.13.x".

If 0.14 isn't supported, this is also a request to support it. Thanks!

**Comment by wagnst** [comment]
There is even 0.15 out now. Please incorporate that info as well! Thanks!

**Comment by inc1t3Ful** [comment]
Hi all, 0.14 will be officially supported in the upcoming R2.19.0 release, alongside Controller version 6.4 very soon. ETA 2 weeks

**Comment by inc1t3Ful** [comment]
Hi all, R2.19 has been released. 

https://registry.terraform.io/providers/AviatrixSystems/aviatrix/latest
https://registry.terraform.io/providers/AviatrixSystems/aviatrix/latest/docs/guides/release-notes#2190

Thank you all for your patience!
