### ISSUE TITLE
Feature request: Support tagging of ELB and GATEWAY through terraform

### ISSUE THREAD

**Issue by infa-apatel** [AviatrixSystems/terraform-provider-aviatrix#88]
Our cloud accounts monitor for specific tags for EC2 and RDS servers, and if they don't have the required tags, they will be shutdown.  This can cause interruption in initializing the aviatrix VPN gateway and result in unknown state.  We are looking for support to tag the ELB and GATEWAY through terraform.

**Comment by arvindsree** [comment]
Thank you for the request. We are analyzing this

**Comment by arvindsree** [comment]
Tagging of gateway resources can be supported on terraform

ELB tagging however needs support on the controller. An feature request(ref 7697) has been filed. It is better to go though sales/support to prioritize it.

**Comment by zhiqiangjin** [comment]
Terraform supports gateway tagging now.

**Comment by arvindsree** [comment]
Moved to https://github.com/terraform-providers/terraform-provider-aviatrix/issues/34
