### ISSUE TITLE
Feature Request: Return HA Security Group ID

### ISSUE THREAD

**Issue by aaronmell** [AviatrixSystems/terraform-provider-aviatrix#908]
**Is your feature request related to a problem? Please describe.**
Would like to be able to set additional security group rules automatically on both primary and HA gateways (egress and transit), so we don't have to manually set those rules. 

**Describe the solution you'd like**
an attribute ha_security_group_id to be returned from both aviatrix_gateway and aviatrix_transit_gateway resources

**Comment by CyrusJavan** [comment]
Hi @aaronmell,
Thanks for bringing up this feature request, that is a great idea! I have created a ticket in our internal issue tracker and we will aim to get this feature added in a future release. Thanks!
