### ISSUE TITLE
Importing an aviatrix_fqdn resource doesn't respect manage_domain_names

### ISSUE THREAD

**Issue by aaronmell** [AviatrixSystems/terraform-provider-aviatrix#909]
**Describe the problem**

If I have an existing fqdn that I import with manage_domain_names set to false, terraform wants to remove all the rules from the fqdn. 

**To Reproduce**

Create an fqdn in the controller
Create a aviatrix_fqdn resource in terraform with manage_domain_names = false
Import the existing fqdn created in the controller.
Run a plan

If possible, provide steps to reproduce the behavior:

**Expected behavior**
I would expect when manage_domain_names is set to false, it won't modify any of the rules after import. IE: importing with manage_domain_names false doesn't also import the domain_names and try to immediately remove them

**Environment:**
 - Provider version: 2.18.2
 - Terraform version: v0.12.29
 - Aviatrix Controller version: UserConnect-6.3.2364

**Additional context**
We want to manage the fqdn resource via terraform. However, we manage the rules manually today, eventually with the api.

**Comment by aaronmell** [comment]
I'm pretty sure the issue is here 

https://github.com/AviatrixSystems/terraform-provider-aviatrix/blob/eef9c3d7d0511fda7d3094c2ef9a5b9f3ef2e16a/aviatrix/resource_aviatrix_fqdn.go#L231

It always sets manage_domain_names to true, when it should be reading the value passed in.

**Comment by CyrusJavan** [comment]
Hi @aaronmell,
Thanks for bringing this up. The behavior you describe is the intended behavior when importing a resource with a `manage_*` attribute, however, it did lead to me uncovering a bug in the `aviatrix_fqdn` resource. Please see the description of PR #914 for an explanation of the bug and the seemingly odd behavior of `terraform import` and `manage_domain_names` that you describe here.
