### ISSUE TITLE
Support for terraform 0.15

### ISSUE THREAD

**Issue by hylaride** [AviatrixSystems/terraform-provider-aviatrix#918]
Terraform 0.15 is out.  Aviatrix is keeping our TF version out of date without support for it.

**Comment by wagnst** [comment]
0.14 support was released yesterday. 0.15 would be nice now as well. Any idea when it will come?

**Comment by deutmeyerbrianpfg** [comment]
Looks like 0.15.x is now supported: https://github.com/AviatrixSystems/terraform-provider-aviatrix/blob/master/docs/guides/release-compatibility.md

**Comment by hylaride** [comment]
Right on time for the 1.0 release! 😏

**Comment by CyrusJavan** [comment]
Closing this as 0.15.x support was added with v2.19.3 and 1.x.x support was added in v2.19.5.
